FROM ubuntu:22.04
RUN apt update
ARG DEBIAN_FRONTEND=noninteractive
ENV TERM xterm-256color
RUN apt-get update && \
      apt-get -y install sudo

RUN apt-get install -y gcc-multilib
RUN apt-get install -y g++-multilib
RUN apt-get install -y libdwarf-dev
RUN apt-get install -y make
RUN apt-get install -y libelf-dev
RUN apt-get install -y libsqlite3-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y doxygen
RUN apt-get install -y gdb
RUN apt-get install -y gcovr

RUN mkdir /home/docker
RUN mkdir /home/docker/juicer
WORKDIR /home/docker/juicer

RUN useradd -ms /bin/bash juicer-dev
RUN usermod -aG sudo juicer-dev
RUN echo "juicer-dev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER juicer-dev
