name: Run juicer tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Clone submodules
          fetch-depth: 0    # Ensure full repository history is fetched

      # Set up Docker Buildx (optional, useful for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      # - name: Build Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: false  # Do not push the image
      #     tags: juicer:latest  # Local tag for the built image

      - name: Build Docker image
        run: docker build --no-cache -t juicer:latest -f Dockerfile . 
      - name: Copy coverage report to host
        run: docker image ls && img_id=$(docker create juicer:latest) && docker cp $img_id:/home/docker/juicer/coverage.gcov .
      - name: publish to coveralls.io
        run: wget https://github.com/coverallsapp/coverage-reporter/releases/download/v0.6.14/coveralls-linux && chmod a+x ./coveralls-linux && COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} ./coveralls-linux
